// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzooliaejcbeffxttknv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6b29saWFlamNiZWZmeHR0a252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzNTY3MjAsImV4cCI6MjA3NjkzMjcyMH0.laMQr_tmPGaU5mvq5gle9XpVPm6S8ezSQ36qeiPiTo0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});